name: CheckStatus

on: workflow_call

permissions:
  contents: read

jobs: 
  check_status:
    runs-on: ubuntu-latest
    outputs:
      check_status: ${{ steps.check_statuses.outputs.found }}
    steps:
      - uses: lwhiteley/dependent-jobs-result-check@v1
        id: check_statuses
        with:
          statuses: failure
          dependencies: ${{toJSON(needs) }}
      - name: Log output
        run: |
          echo "statuses:" "${{ steps.check_statuses.outputs.statuses }}"
          echo "jobs:" "${{ steps.check_statuses.outputs.jobs }}"
          echo "found any?:" "${{ steps.check_statuses.outputs.found }}"  
      - name: Cancel if failure
        if: ${{ steps.check_statuses.outputs.found == 'true' }}
        run: |
          exit 1